on:
  push:
    branches:
      - main
    paths:
      - "website/**"
      - "renv.lock"
      - ".github/workflows/publish.yml"

name: Render and Publish

permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: 📘 Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.55
          tinytex: false

      - name: Install system deps
        run: sudo apt-get install -y libcurl4-openssl-dev

      # - name: 🆙 Setup R
      #   uses: r-lib/actions/setup-r@v2

      # - name: 📦 Install dependencies with renv
      #   uses: r-lib/actions/setup-renv@v2
      #   with:
      #     cache-version: 1

      # - name: 📦 Install website dependencies
      #   shell: Rscript {0}
      #   run: |
      #     renv::activate()
      #     pak::pak(dependencies = "Config/Needs/website")

      - name: 📰 Render and Publish to GitHub Pages
        uses: gadenbuie/quarto-actions/publish@quarto-render-working-dir
        with:
          target: gh-pages
          working-directory: website
